apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ngnr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ngnr
    app.kubernetes.io/part-of: byoc-app-aabz
  name: ngnraser
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: ngnr
    weight: null
status: {}
